/** Type of a single unit generated by the syntax_highlight utility script. */
export interface CodeBlockContentUnit {
  /** The content of the code block. */
  readonly content: string;
  /** Token type of the content. */
  readonly type: string;
}

/**
 * Array of lines of code, where each line contains content units.
 * This matches the type of the output from the syntax_highlight utility script.
 */
export type CodeBlockContent = CodeBlockContentUnit[][];
